### ISSUE TITLE
Homebrew tap

### ISSUE THREAD

**Issue by Nepherte** [TheAppgineer/roon-tui#2]
I made a homebrew tap to install roon-tui on macOS: https://github.com/Nepherte/homebrew-roon.

Tested on both Intel-based and Arm-based macs. Feel free to provide feedback.

If you'd rather take ownership of the hombrew tap, more than happy to transfer it over.

**Comment by JanKoudijs** [comment]
Thanks for creating this!

I'm not in the Apple ecosystem and am not familiar with Homebrew, so no need for me to have any ownership here.

Do you have any suggestion on what I should add to README to make users aware this exists and how to use it?

Edit: I will start by including the link you provided, that is probably already enough.

**Comment by JanKoudijs** [comment]
Added to the README

https://github.com/TheAppgineer/roon-tui/commit/2c73cf60bd4a54c889401757309c34c8ec35a111

**Comment by Nepherte** [comment]
> Added to the README

Looks good to me.

> Do you have any suggestion on what I should add to README to make users aware this exists and how to use it?
> 
> Edit: I will start by including the link you provided, that is probably already enough.

I'm hoping the instructions on my repo suffice. It's literally the 2 commands that are listed there, apart from having to install Homebrew, which I'm hoping people already have installed if they arrive at that page. Then again, it's internet... so I might just link to the Homebrew page for the one line install command.
