### ISSUE TITLE
Location of config.json

### ISSUE THREAD

**Issue by Nepherte** [TheAppgineer/roon-tui#3]
Right now, roon-tui always looks for a config.json file in the folder from which the command is run. So if you run roon-tui from a new folder, you'll have to authorize a new extension instance in new. 

# Steps to reproduce
Open a terminal and execute:
```
$ cd /path/to/some/folder
$ roon-tui 
```
Authorize the extension with a Roon Remote. 
=> This will produce a `config.json` in `/path/to/some/folder`.

Now, close the app with `ctrl + c` and execute:

```
$ cd /path/to/some/other/folder
$ roon-tui 
```
=> No core is paired / found.

Instead, you'll have to authorize a new extension with a Roon Remote.
=> This will produce a `config.json` in `/path/to/some/other/folder`.
=> Now there are 2 roon-tui instances authorized in Roon.

What I would like is that it uses the initially authorized extension instance (ie. re-use the first config.json)

# Proposed solution
Ideally, the config.json goes into a fixed location in the home folder (e.g. ~/.config/roon-tui/config.json).

**Comment by JanKoudijs** [comment]
I realized the same and already had a look on what it would take to fix.
There is no quick fix as it also affects the underlying rust-roon-api.
But now it is on the list so I probably will get to it.

**Comment by Nepherte** [comment]
For now, I'm just using the following alias as a workaround:
```
alias roon-tui="pushd ~/.config/roon-tui > /dev/null; roon-tui; popd > /dev/null"
```

When doing `setopt pushdsilent` (in zsh), it can be shortened to:
```
alias roon-tui="pushd ~/.config/roon-tui; roon-tui; popd"
```

**Comment by JanKoudijs** [comment]
Version 0.0.4 allows you to specify the config.json file on the command line:

https://github.com/TheAppgineer/roon-tui#specifying-configuration-file-on-command-line

Closing this now.
