### ISSUE TITLE
Shortcut to switch between views

### ISSUE THREAD

**Issue by Nepherte** [TheAppgineer/roon-tui#4]
Currently, you can use `Tab` to forward cycle between views. Would be great to add  `Shift + Tab` to backwards cycle between views. It is quite common and OS-agnostic to e.g. shift the focus to the next ui element in an application (e.g. text fields). Operating systems, e.g. macOS, also allows does something similar to switch between applications (ie. `Cmd + Tab` and `Cmd + Shift + Tab`)

**Comment by JanKoudijs** [comment]
Good suggestion, will be in the next release.

https://github.com/TheAppgineer/roon-tui/commit/34b78d5fbbfedcf410fd924a418b6284b87da8c7
