### ISSUE TITLE
Ability to browse library when no zone is present / selected

### ISSUE THREAD

**Issue by Nepherte** [TheAppgineer/roon-tui#7]
When I use roon-tui without a zone present (ie. all my streamers are off), I would still like to be able to browse my library. This is currently not possible. To be more specific, when I try to press enter, nothing happens:

<img width="1048" alt="Screenshot 2023-08-26 at 6 51 16 PM" src="https://github.com/TheAppgineer/roon-tui/assets/55176/371e0141-3016-4fc1-8cd3-5db165ce4eec">

**Comment by JanKoudijs** [comment]
Any difference in behavior after pressing F5 to refresh?

**Comment by Nepherte** [comment]
Strange thing is that, now that I'm trying it again, the initial screen is this:

<img width="1048" alt="Screenshot 2023-08-29 at 10 36 20 AM" src="https://github.com/TheAppgineer/roon-tui/assets/55176/e238ddb5-f427-4578-a62e-e30ee0ebc867">

Either way, whichever item I want to select, Pressing \<enter\> does not go into the menu. Pressing \<F5\> doesn't seem to make a difference either.

**Comment by Nepherte** [comment]
@JanKoudijs Any chance you were able to look into this? Is this expected and should there be a zone active in order to browse, or should it work without there being a zone?

**Comment by JanKoudijs** [comment]
@Nepherte I had a look today and it will be fixed in the next release. You will be able to browse till the playback level is reached and the empty zone selector is hit.

**Comment by JanKoudijs** [comment]
Fixed in [Version 0.3.0](https://github.com/TheAppgineer/roon-tui/releases/tag/0.3.0)
