### ISSUE TITLE
Show remaining queue time

### ISSUE THREAD

**Issue by Nepherte** [TheAppgineer/roon-tui#8]
I would love for roon-tui to show the remaining time of the queue. 

In the example below, it would be around 6:38 (2:46 + 3:29 + 2:49 - 2:36). To me, it makes most sense to show this info somewhere at the queue pane border (similar how the queue label is shown). 

A similar case could be made for the number of tracks still in the queue, but to me, remaining time is more useful to know.

<img width="1004" alt="Screenshot 2023-08-28 at 3 42 33 PM" src="https://github.com/TheAppgineer/roon-tui/assets/55176/892bc529-abcf-4c3b-a1ed-42ef5460c257">

**Comment by JanKoudijs** [comment]
Implemented in [Version 0.0.5](https://github.com/TheAppgineer/roon-tui/releases/tag/0.0.5).

Number of items remaining was already in and is shown when the Queue view is active, now the remaining time is shown when Queue is not the active view.

btw. no need for calculations as the remaining queue time is provided by the Roon API :)
